name: Check
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
      - .gitignore
      - .gitattributes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: tests/uv.lock
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: tests/.python-version
      - name: Install dependencies
        run: make -C tests sync
      - name: Check formatting
        run: make -C tests check-format
      - name: Lint
        run: make -C tests check-lint
      - name: Check types
        run: make -C tests check-types
      - name: Set Git author info
        run: |
          git config --global user.name GHA
          git config --global user.email actions@github.com
      - name: Run tests
        run: make -C tests run
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
